package com.networker.entity;
// Generated 26/06/2016 07:14:52 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contenido generated by hbm2java
 */
@Entity
@Table(name="contenido"
    ,catalog="networker"
)
public class Contenido  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String precontenido;
     private String urlImgPrecontenido;
     private String contenido;
     private String urlImgContenido;
     private String principal;
     private Date fechacreacion;
     private Integer idcategoria;
     private String pre;
     private String tipoVista;
     private String url;

    public Contenido() {
    }

    public Contenido(String nombre, String precontenido, String urlImgPrecontenido, String contenido, String urlImgContenido, String principal, Date fechacreacion, Integer idcategoria, String pre, String tipoVista, String url) {
       this.nombre = nombre;
       this.precontenido = precontenido;
       this.urlImgPrecontenido = urlImgPrecontenido;
       this.contenido = contenido;
       this.urlImgContenido = urlImgContenido;
       this.principal = principal;
       this.fechacreacion = fechacreacion;
       this.idcategoria = idcategoria;
       this.pre = pre;
       this.tipoVista = tipoVista;
       this.url = url;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="nombre", length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="precontenido", length=65535)
    public String getPrecontenido() {
        return this.precontenido;
    }
    
    public void setPrecontenido(String precontenido) {
        this.precontenido = precontenido;
    }

    
    @Column(name="url_img_precontenido", length=60)
    public String getUrlImgPrecontenido() {
        return this.urlImgPrecontenido;
    }
    
    public void setUrlImgPrecontenido(String urlImgPrecontenido) {
        this.urlImgPrecontenido = urlImgPrecontenido;
    }

    
    @Column(name="contenido", length=65535)
    public String getContenido() {
        return this.contenido;
    }
    
    public void setContenido(String contenido) {
        this.contenido = contenido;
    }

    
    @Column(name="url_img_contenido", length=60)
    public String getUrlImgContenido() {
        return this.urlImgContenido;
    }
    
    public void setUrlImgContenido(String urlImgContenido) {
        this.urlImgContenido = urlImgContenido;
    }

    
    @Column(name="principal", length=60)
    public String getPrincipal() {
        return this.principal;
    }
    
    public void setPrincipal(String principal) {
        this.principal = principal;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechacreacion", length=10)
    public Date getFechacreacion() {
        return this.fechacreacion;
    }
    
    public void setFechacreacion(Date fechacreacion) {
        this.fechacreacion = fechacreacion;
    }

    
    @Column(name="idcategoria")
    public Integer getIdcategoria() {
        return this.idcategoria;
    }
    
    public void setIdcategoria(Integer idcategoria) {
        this.idcategoria = idcategoria;
    }

    
    @Column(name="pre", length=60)
    public String getPre() {
        return this.pre;
    }
    
    public void setPre(String pre) {
        this.pre = pre;
    }

    
    @Column(name="tipo_vista", length=60)
    public String getTipoVista() {
        return this.tipoVista;
    }
    
    public void setTipoVista(String tipoVista) {
        this.tipoVista = tipoVista;
    }

    
    @Column(name="url", length=100)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }




}


